name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.yarnpkg.com/

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Run tests
        run: yarn test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.yarnpkg.com/

      - name: Install dependencies
        run: yarn install --production --frozen-lockfile

      - name: Deploy to production
        run: |
          # Prisma database migration
          npx prisma migrate deploy --preview-feature

          # Restart server or deploy new version
          # Adjust the command according to your deployment strategy
          pm2 restart server.js
